// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ToDoListAPI
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for ToDoList.
    /// </summary>
    public static partial class ToDoListExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='owner'>
            /// </param>
            public static IList<ToDoItem> GetByOwner(this IToDoList operations, string owner)
            {
                return Task.Factory.StartNew(s => ((IToDoList)s).GetByOwnerAsync(owner), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='owner'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<ToDoItem>> GetByOwnerAsync(this IToDoList operations, string owner, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByOwnerWithHttpMessagesAsync(owner, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='todo'>
            /// </param>
            public static void PutByTodo(this IToDoList operations, ToDoItem todo)
            {
                Task.Factory.StartNew(s => ((IToDoList)s).PutByTodoAsync(todo), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='todo'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PutByTodoAsync(this IToDoList operations, ToDoItem todo, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.PutByTodoWithHttpMessagesAsync(todo, null, cancellationToken).ConfigureAwait(false);
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='todo'>
            /// </param>
            public static void PostByTodo(this IToDoList operations, ToDoItem todo)
            {
                Task.Factory.StartNew(s => ((IToDoList)s).PostByTodoAsync(todo), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='todo'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostByTodoAsync(this IToDoList operations, ToDoItem todo, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.PostByTodoWithHttpMessagesAsync(todo, null, cancellationToken).ConfigureAwait(false);
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='owner'>
            /// </param>
            /// <param name='id'>
            /// </param>
            public static ToDoItem GetByIdByOwnerAndId(this IToDoList operations, string owner, int id)
            {
                return Task.Factory.StartNew(s => ((IToDoList)s).GetByIdByOwnerAndIdAsync(owner, id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='owner'>
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ToDoItem> GetByIdByOwnerAndIdAsync(this IToDoList operations, string owner, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByIdByOwnerAndIdWithHttpMessagesAsync(owner, id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='owner'>
            /// </param>
            /// <param name='id'>
            /// </param>
            public static void DeleteByOwnerAndId(this IToDoList operations, string owner, int id)
            {
                Task.Factory.StartNew(s => ((IToDoList)s).DeleteByOwnerAndIdAsync(owner, id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='owner'>
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteByOwnerAndIdAsync(this IToDoList operations, string owner, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.DeleteByOwnerAndIdWithHttpMessagesAsync(owner, id, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
